spring:
  application:
    name: hlt-api-gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: hlt-food-service
          uri: lb://HLT-FOOD-SERVICE
          predicates:
            - Path=/foods/**
        - id: hlt-bmi-calc-service
          uri: lb://HLT-BMI-CALC-SERVICE
          predicates:
            - Path=/bmi-calc/**
        - id: hlt-bmr-calc-service
          uri: lb://HLT-BMR-CALC-SERVICE
          predicates:
            - Path=/bmr-calc/**
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8081

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://hlt-discovery-service:8761/eureka
