spring:
  application:
    name: hlt-api-gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: hlt-food-service
          uri: lb://HLT-FOOD-SERVICE
          predicates:
            - Path=/foods/**
        - id: hlt-bmi-calc-service
          uri: lb://HLT-BMI-CALC-SERVICE
          predicates:
            - Path=/bmi-calc/**
        - id: hlt-bmr-calc-service
          uri: lb://HLT-BMR-CALC-SERVICE
          predicates:
            - Path=/bmr-calc/**
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8080/realms/My-Realm
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: hlt-api-gateway-service
            client-secret: Z6VwWqaDUGGRT5VtupNQnMsdz7xXAfD8
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"